# Python Data, 2024

---

* Úvod do NUMPY,
* základy NUMPY,
    - atributy,
    - metody,
    - spojování,
    - rozdělování,
    * cvičení 1,
    * cvičení 2,
* univerzální funkce, ~ufuncs,
    - úvod
    - typy funkcí
    * cvičení 3.

## Úvod do NUMPY

---

<img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.QQOtOJPya2YEO6IkVBnYjQHaDV%26pid%3DApi&f=1&ipt=245c27df971ff24527ca317988f6feda8b14851ef0a889fda7d5a10d114dc5e6&ipo=images" width="300" style="margin-left:auto; margin-right:auto"/>

### Proč umět NUMPY

---

Je to univerzální knihovna pro práci **s numerickými daty** v jazyce Python.

Funkcionalita této knihovny je využívána (skrze API) v jiných knihovnách jako *Pandas*, *SciPy*, *Matplotlib*, *scikit-learn*, *scikit-image*.

<br>

Nabízí efektivní nástroje pro práci **s většími datovými strukturami**.

Usnadňuje práci se **vícerozměrnými poli** a **maticovými datovými strukturami**.

### Kde zjistit více informací

---

Dokumentaci najdeš [zde](https://numpy.org/doc/stable/index.html#).

Zdrojový kód najdeš [zde](https://github.com/numpy/numpy).

### Jak jej nainstaluji

---

Instalace knihovny obecně (doporučeno v rámci virtuálního prostředí):

In [ ]:
!pip install numpy

...nebo:

In [ ]:
!conda install numpy

<br>

Nahrávání knihovny:

In [1]:
import numpy

In [2]:
import numpy as np

In [3]:
from numpy import array

<br>

Používaná verze knihovny:

In [4]:
numpy.__version__

'1.24.4'

### Srovnání datových typů

---

Efektivní práce s daty si zakládá na tom, jak jsou data uložená.

Proto je zásadní tušit jak objekty zpracovává **klasický Python** a `numpy`.

In [5]:
x: int = 10
x: float = 10.0
x: str = "deset"

*Dynamické typování* v Pythonu vypadá jako dobrý nápad.

Přináší jistou flexibilitu a jednodušší používání.

Také s sebou ovšem nese jisté povinnosti, které by obyčejná proměnná **neměla normálně zpracovávat**.

V ukázce neukládáš pouze hodnoty, ale další doprovodné informace:
* **počet referencí**, kvůli alokaci/dealokaci paměti,
* **typ kódovací sady**,
* **velikost** následujících dat.

#### LIST v Pythonu

---

In [6]:
muj_list: list = [10, 10.0, "deset"]

In [7]:
datove_typy_listu = [type(hodnota) for hodnota in muj_list]

In [8]:
datove_typy_listu

[int, float, str]

<br>

Je jasné, že tento *komfort* sebou nese i svoji cenu.

Protože toho každá hodnota s sebou nese další doplňující informace (datový typ, kódování, ...).

I kdyby byly hodnoty stejného datové typu, přesto s sebou přenášejí řadu balastu.

Tomu se snaží knihovna `numpy` pomáhat.

In [9]:
from numpy import array

In [10]:
ciselne_pole = array(range(6))

In [11]:
ciselne_pole

array([0, 1, 2, 3, 4, 5])

In [12]:
ciselne_pole.dtype

dtype('int64')

In [13]:
type(ciselne_pole)

numpy.ndarray

<br>

Na rozdíl od datového typu`list` v jazyce Python, pole v `numpy` obsahují stejný datový typ.

Pokud tomu tak není, `numpy` provede *upcast* (představ si datovou konverzi):

In [14]:
mix_desetinne_cele_hodnoty = array((1, 2, 3, 3.1416))

In [15]:
mix_desetinne_cele_hodnoty

array([1.    , 2.    , 3.    , 3.1416])

In [16]:
mix_desetinne_cele_hodnoty.dtype

dtype('float64')

<br>

Pokud potřebuješ dodržet konkrétní datový typ, použij explicitně *parametr* `dtype`:

In [17]:
jen_cele = array((1, 2, 3, 3.1416), dtype="int64")

In [18]:
jen_cele

array([1, 2, 3, 3])

<br>

Datové typy se snaží implicitně konvertovat. Pokud je to možné.

In [19]:
jen_cele = array((1, 2, "tři", 3.1416), dtype="int64")  # "tři" --> 3

ValueError: invalid literal for int() with base 10: 'tři'

In [20]:
int("tři")

ValueError: invalid literal for int() with base 10: 'tři'

In [21]:
jen_cele

array([1, 2, 3, 3])

<br>

`numpy` nabízí obrovskou škálu rychlých a efektivních způsobů vytváření polí a manipulace s číselnými daty v nich.

Pracuje s homogenními sekvenčnímy objekty.

#### Proč používat NUMPY?

---

Pole v `numpy` jsou rychlejší a kompaktnější než `list` v Pythonu.

Pole spotřebovává **méně paměti a pohodlně se používá** (určení datových typů,..).

```
Země   Počet obyv.   Rozloha
česká republika 11  75
německo         22  115
rakousko        15  70
```

In [22]:
import numpy as np
from pandas import DataFrame

In [23]:
zeme_df = DataFrame(
    data=[[11, 79], [66, 243], [196, 924]],
    index=["CZE", "UK", "Nigeria"],
    columns=["population", "surface_area"]
)

In [24]:
zeme_df

population  surface_area
CZE              11            79
UK               66           243
Nigeria         196           924

In [25]:
zeme_arr = np.array(zeme_df)

In [26]:
zeme_arr

array([[ 11,  79],
       [ 66, 243],
       [196, 924]])

In [27]:
zeme_arr.dtype

dtype('int64')

<br>

## Základy NUMPY

---

Protože je `numpy` postaven na jazyku C, přebírá také podobné datové typy.

Některé datové typy:
    
| Datový typ v `numpy` | Popis |
| :- | :- |
| `bool_` | boolean `True`, `False` |
| `int16` | celá čísla (bajty od -32768 do 32767) |
| `int32` | celá čísla (bajty od -2147483648 do 2147483647)) |
| `int64` | celá čísla (bajty od -9223372036854775808 to 9223372036854775807) |
| `float64` | desetinné čísla |
| `complex64` | komplexní čísla, reprezentovaná dvěma 64-bitovými dese. čísly |

<br>

Dále `numpy` poskytuje `array` objekty.

In [ ]:
muj_list = [1, 2, 3]                      # 1D
muj_2D_list = [[1, 2], [3, 4]]            # 2D pole == matice
muj_3D_list = [[[1, 2], [2, 3]], [[..]]]  # 3D

Ty slouží jako prostředky pro elegantní manipulaci s daty (znáš z `pandas`).

Základní operace pro `array`:
* **atributy**,
* **indexování**,
* **řezání**,
* **RESHAPE**,
* **JOIN** a **MERGE** --> *konkatenace*, *split*

### Vytvoření ARRAY

---

In [28]:
import numpy as np

<br>

#### Pomocí built-in sekvencí

---

Můžeš jednoduše konvertovat built-in datové typy v Pythonu na `numpy` pole:

In [29]:
muj_range: range = range(3)
muj_list: list = [3, 4, 5]
muj_tuple: tuple = (6, 7, 8)

In [30]:
muj_list_arr = np.array(muj_list)
muj_tuple_arr = np.array(muj_tuple)
muj_range_arr = np.array(muj_range)

In [ ]:
muj_list_arr

In [31]:
type(muj_list_arr)

numpy.ndarray

<br>

Atribut `dtype` neví nic o datovém typu objektu, jen jakým objekty je naplněný:

In [32]:
muj_list_arr.dtype

dtype('int64')

In [37]:
isinstance(muj_list_arr, np.ndarray)

True

In [38]:
type(muj_tuple_arr)

numpy.ndarray

<br>

#### Pomocí nul, funkce `zeros`

---

In [42]:
jen_nuly = np.zeros([2, 5])  # Royal (rows) Crown (columns) cola 

In [43]:
jen_nuly

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [41]:
jen_nuly.dtype

dtype('float64')

<br>

Pro jiný datový typ je potřeba explicitně zadat hodnotu:

In [42]:
jen_nuly = np.zeros([2, 5], dtype='int64')  # Royal (rows) Crown (columns) cola 

In [43]:
jen_nuly

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

<br>

#### Pomocí jedniček, funkce `ones`

---

In [44]:
jen_jednicky = np.ones(shape=(2, 3), dtype=int)

Definice nového pole je možná i s klíčovými argumenty (parametr `shape`).

In [ ]:
# np.ones?

In [45]:
jen_jednicky.dtype

dtype('int64')

In [46]:
jen_jednicky

array([[1, 1, 1],
       [1, 1, 1]])

<br>

#### Pomocí defaultní výplňové hodnoty, funkce `full`

---

In [47]:
jen_pi = np.full(shape=(3, 5), fill_value=np.pi)  # math, math.pi

In [48]:
jen_pi

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265]])

<br>

#### Pomocí rozsahů, funkce `arange`

---

Velmi intuitivně zadavaná datová struktura, podobně jako u Python `range`:

In [49]:
interval_arr = np.arange(start=0, stop=10, step=1)

In [50]:
interval_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
type(interval_arr)

numpy.ndarray

In [52]:
interval_arr.dtype

dtype('int64')

<br>

Narozdíl od standardní knihovny umí `numpy` arrange objekt tvořit intervaly i s pomocí desetinných čísel.

In [55]:
interval_arr = np.arange(start=0, stop=1, step=0.1, dtype='float64')

In [56]:
interval_arr

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

<br>

#### Pomocí náhodných celých čísel, funkce `random`

---

In [57]:
# from random import randint

In [58]:
random_hodnoty = np.random.randint(low=0, high=6, size=(2, 4))

In [59]:
random_hodnoty

array([[0, 0, 1, 3],
       [2, 3, 0, 0]])

In [61]:
type(random_hodnoty)

numpy.ndarray

In [64]:
poradi = len(range(10))  # 10

<br>

Občas je vhodnější tvořit rozsahy dynamicky, než statickou (hárdkódovanou) hodnotou:

In [65]:
random_hodnoty = np.random.randint(low=0, high=66, size=poradi)

In [66]:
tuple(random_hodnoty)

(58, 53, 63, 52, 48, 47, 55, 55, 54, 37)

<br>

#### Jednodimenzionální pole

---

In [70]:
m1 = np.random.randint(low=1, high=10, size=6)

In [71]:
m1

array([1, 6, 3, 9, 4, 4])

<br>

Tedy prakticky jednoduché pole, které se na první pohled neliší tolik od `list`.

#### Dvoudimenzionální pole

---

In [74]:
m2 = np.random.randint(10, size=(2, 3))

In [75]:
m2

array([[3, 9, 8],
       [3, 0, 6]])

<br>

Definicí oznamuješ:
1. `10`, vyber náhodné celé čísla z intervalu `0-9`,
2. vytvoř **2 řádky**,
3. .. o **3 sloupcích**.

#### Třídimenzionální pole

---

In [78]:
m3 = np.random.randint(10, size=(2, 3, 4))  # implicitní zadání "high"

In [79]:
m3

array([[[3, 3, 5, 6],
        [5, 5, 6, 0],
        [3, 5, 2, 6]],

       [[8, 9, 6, 0],
        [6, 6, 0, 6],
        [7, 0, 6, 4]]])

<br>

Definicí oznamuješ:
1. `10`, vyber náhodné celé čísla z intervalu `0-9`,
2. vytvoř **2 matice**,
3. .. o **3 řádcích**,
4. .. a **4 sloupcích**.

<br>

### Atributy pro ARRAY

---



Pokud budeš potřebovat prozkoumat existující `array`, můžeš vyzkoušet tyto atributy a metody:
1. **Dimenze**,
2. **tvar**,
3. **velikost**,
4. **datové typy**,
5. **bajtová velikost**.

#### Dimenze matice

---

In [80]:
m3.ndim

3

In [81]:
m2.ndim

2

<br>

#### Tvar matice

---

In [82]:
m3.shape

(2, 3, 4)

In [83]:
m2.shape

(2, 3)

In [84]:
m2

array([[3, 9, 8],
       [3, 0, 6]])

<br>

#### Velikost matice

---

In [ ]:
m3.size

<br>

#### Datový typ

---

In [ ]:
m3.dtype

<br>

#### Velikost v bajtech

---

In [ ]:
m3.nbytes

<br>

Jde o součin atributů **size** * **itemsize**.

<br>

### Indexování ARRAY

---



Postup vypadá podobně jako pro sekvenční datové typy v Pythonu.

Pomocí hranaté závorky a celého čísla, můžeš zpřístupnit konkrétní hodnotu/ hodnoty.

<br>

##### Jednodimenzionální

In [ ]:
m1

In [ ]:
m1[0]

In [ ]:
m1[1]

In [ ]:
m1[-1]

<br>

##### Dvoudimenzionální

In [ ]:
m2

In [ ]:
m2[0]

In [ ]:
m2[0][0]

In [ ]:
m2[0, 0]

<br>

Pomocí indexů zpřístupníš hodnotu na konkrétní pozici a můžeš ji modifikovat:

In [ ]:
m2

In [ ]:
el_m2 = m2[0, 0]

In [ ]:
el_m2

In [ ]:
m2[0, 0] = 11

In [ ]:
m2

<br>

Dávej pozor na datové typy. Pokud budeš chtít přidat jiný datový typ:

In [ ]:
m2[0, 0] = 11.111

In [ ]:
m2

Výsledek bude na pozadí *truncatovaný*.

In [ ]:
m2[0, 0] = "jedenáct"

<br>

### Slicing ARRAY

---



Podobně jako u zpřístupňování jednotlivých hodnot, můžeš tvořit *subarrays*.

Postup je opět velmi podobný pro *slicing* u sekvenčních hodnot.

Je doporučené udávat všechny argumenty, protože implicitní dosazování defaultních hodnot může mást uživatele.

In [ ]:
zeme_arr

In [ ]:
zeme_arr[0:2]

In [ ]:
zeme_arr[-2:]

<br>

Pro více dimenzí, dva řádky a jeden sloupec:

In [ ]:
dva_radky_jeden_sloupec = zeme_arr[:2, :1]

In [ ]:
dva_radky_jeden_sloupec

In [ ]:
dva_radky_jeden_sloupec = zeme_arr[::2, :1]

In [ ]:
dva_radky_jeden_sloupec

<br>

Pokud pracuješ se *subarrays*, používáš pohledy originální hodnoty.

V Pythonu to byla většinou kopie, původního objektu:

In [ ]:
dva_radky_jeden_sloupec

In [ ]:
dva_radky_jeden_sloupec[0, 0] = 13

In [ ]:
dva_radky_jeden_sloupec

In [ ]:
zeme_arr

<br>

Pokud potřebuješ přesto nachystat kopii a ponechat původní hodnoty nezměněné, vyzkoušej metodu `copy`:

In [ ]:
kopie_dva_radky_jeden_sloupec = zeme_arr[:2, :1].copy()

In [ ]:
kopie_dva_radky_jeden_sloupec

In [ ]:
kopie_dva_radky_jeden_sloupec[0, 0] = 22

In [ ]:
kopie_dva_radky_jeden_sloupec

In [ ]:
zeme_arr

<br>

### Přetváření ARRAY

---



Jestli budeš potřebovat změnit tvar pole nebo matice, vyzkoušej metodu `reshape`:

In [ ]:
zeme_df

In [ ]:
zeme_arr[0, 0] = 11

In [ ]:
zeme_arr

<br>

Vytvoříš si jednodimenzionální pole s pomocí funkce `arange`:

In [ ]:
pole_1D = np.arange(1, 11)

In [ ]:
pole_1D

<br>

Nachystám 2D pole, matici, pomocí metody `reshape`:

In [ ]:
matice = pole_1D.reshape(2, 5)

In [ ]:
matice

<br>

Pomocí metody `reshape` můžeš také měnit **řádkový vektor za sloupcový**:

In [ ]:
import numpy as np

In [ ]:
radkovy_vektor = np.array((11, 22, 33, 44))

In [ ]:
radkovy_vektor

In [ ]:
r =  radkovy_vektor[np.newaxis, :]

In [ ]:
r

In [ ]:
r.T

In [ ]:
radkovy_vektor[:, np.newaxis]

In [ ]:
x = np.expand_dims(radkovy_vektor, axis=1)

In [ ]:
x = np.expand_dims(radkovy_vektor, axis=0)

In [ ]:
# np.expand_dims?

In [ ]:
x

#### Ukázka

---

Potřebuješ převést 1D pole na 2D matici, kde budeš mít 7 hodnot na řádek.

In [ ]:
temp_data = np.random.uniform(15, 36, size=30*7)  # 1D

In [ ]:
# temp_data

In [ ]:
temp_data.shape

In [ ]:
temp_data.ndim

In [ ]:
############ Po Ut St Ct Pa So Ne
#01. tyden
#02. tyden
#03.
#...

In [ ]:
temp_data.reshape(2, 7)

In [ ]:
temp_data.reshape(-1, 7)

In [ ]:
tydenni_temp_data = temp_data.reshape(-1, 7)

In [ ]:
# tydenni_temp_data

In [ ]:
tydenni_temp_data.shape

In [ ]:
tydenni_temp_data.ndim

<br>

### Spojování a rozdělování

---



Předchozí ukázky se vztahovaly pouze k jednomu poli, k jedné matici.

Teď uvidíš, jak můžeš kombinovat několik těchto typů objektu.

#### Spojování

Pomocí metody `concatenate` spojíš dvě pole nebo dvě matice nebo více objektů:

In [ ]:
pole_1 = np.arange(1, 6)
pole_2 = np.array((6, 7, 8))

In [ ]:
pole_1

In [ ]:
pole_2

In [ ]:
spojene_pole = np.concatenate(pole_1, pole_2)

In [ ]:
spojene_pole = np.concatenate([pole_1, pole_2])

In [ ]:
spojene_pole

In [ ]:
pole_2D_1 = np.random.randint(low=-15, high=15, size=(3, 2))

In [ ]:
pole_2D_1

In [ ]:
pole_2D_2 = np.random.randint(low=-15, high=15, size=(5, 2))

In [ ]:
pole_2D_2

In [ ]:
pole_2D_3 = np.random.randint(low=-15, high=15, size=(3, 2))

In [ ]:
pole_2D_3

In [ ]:
spojene_matice = np.concatenate([pole_2D_1, pole_2D_3], axis=1)

In [ ]:
spojene_matice

In [ ]:
spojene_matice = np.concatenate([pole_2D_1, pole_2D_2], axis=0)

In [ ]:
spojene_matice

<br>

Pokud nemáš pole nebo matice stejného rozměru, je lepší pracovat s funkcemi:
1. `vstack`, vertikální napojení,
2. `hstack`, horizontální napojení,

In [ ]:
pole_1

In [ ]:
pole_2D_1

In [ ]:
rozsirene_2D = np.concatenate([pole_1, pole_2D_1])

In [ ]:
rozsirene_2D = np.vstack([pole_1, pole_2D_1])

In [ ]:
rozsirene_2D = np.vstack([pole_1[:2], pole_2D_1])

In [ ]:
rozsirene_2D

#### Rozdělování

Opakem spojování polí a matic je rozdělování, které je možné provést pomocí funkcí:
1. `split`,
2. `hsplit`,
3. `vsplit`

In [ ]:
rada_arr = np.random.randint(low=100, high=200, size=(12))

In [ ]:
rada_arr.size

In [ ]:
rada_arr

In [ ]:
r1, r2, r3 = np.split(rada_arr, [4, 8])

In [ ]:
r1, r2, r3

Takže dělení probíhá pomocí dělících indexů.

Tedy máš vždy N indexů a N + 1 polí.

In [ ]:
matice = rada_arr.reshape(3, 4)

In [ ]:
matice

In [ ]:
leve_sl, prave_sl = np.hsplit(matice, 2)

In [ ]:
# np.hsplit?

In [ ]:
leve_sl

In [ ]:
prave_sl

In [ ]:
leve_sl, prave_sl = np.hsplit(matice, 3)

In [ ]:
prvni_sl, druhy_sl, treti_sl = np.hsplit(matice, 3)

In [ ]:
prvni_sl, druhy_sl, treti_sl, ctvrty_sl = np.hsplit(matice, 4)

In [ ]:
prvni_sl, druhy_sl, treti_sl, ctvrty_sl

<br>

##### **🧠 CVIČENÍ 🧠, procvič si základy v NUMPY**

In [ ]:
import numpy

In [ ]:
# 01. Použij NUMPY funkci, která vytvoří 1D pole od 5, do 50 po 5ti

<details>
    <summary>▶️ Řešení</summary>
    
    ```python
    np.arange(5, 51, 5)
    ```
</details>

In [ ]:
# 02. Jak vytvoříš stejné pole pomocí funkce RANGE a LIST?

<details>
    <summary>▶️ Řešení</summary>
    
    ```python
    np.array([cislo for cislo in range(5, 51, 5)])
    ```
</details>

In [ ]:
# 03. Jak můžeš vytvořit pole z kapitálek písmen od A do Z?

<details>
    <summary>▶️ Řešení</summary>
    
    ```python
    np.array([chr(index) for index in range(ord("A"), ord("Z") + 1)])
    ```
</details>

In [ ]:
# 04. Jak můžeš vytvořit 1D pole z 6ti náhodných čísel od 1 do 10 (včetně 10)?

<details>
    <summary>▶️ Řešení</summary>
    
    ```python
    np.random.randint(1, 10, size=6)
    ```
</details>

In [ ]:
# 05. Jak vytvoříš 2D matici 4 x 5 pole s náhodnými čísly od 1 do 50 (včetně 50)?

<details>
    <summary>▶️ Řešení</summary>
    
    ```python
    numpy.random.randint(1, 51, size=(4, 5))
    ```
</details>

<br>

##### **🧠 CVIČENÍ 🧠, procvič si základy v NUMPY**

Máš teplotní záznamy získané ze dvou různých meteorologických stanic.

Každá stanice poskytuje teplotní záznamy za posledních 10 dní, které jsou uloženy ve formátu seznamu. Tvým úkolem je:

In [ ]:
import numpy as np

In [ ]:
stanice_c1_teploty = [21.5, 22.3, 20.7, 19.8, 23.1, 22.6, 20.4, 21.8, 22.9, 21.2]
stanice_c2_teploty = [18.5, 19.1, 18.7, 17.8, 21.3, 20.6, 18.5, 19.7, 20.5, 19.2]

In [ ]:
# Převeď seznamy teplot na NumPy pole.

In [ ]:
# spoj oba záznamy do jednoho pole pomocí funkce 'concatenate'.

In [ ]:
# rozděl sloučené pole na dvě části: prvních 5 dní a druhých 5 dní.

In [ ]:
# vypočítej průměrnou teplotu pro prvních 5 dní a druhých 5 dní.

In [ ]:
# Převeď seznamy teplot na NumPy pole.
teploty1_np = np.array( stanice_c1_teploty )
teploty2_np = np.array( stanice_c2_teploty )

In [ ]:
# spoj oba záznamy do jednoho pole pomocí funkce 'concatenate'.
teploty = np.concatenate( [teploty1_np, teploty2_np] )

In [ ]:
# rozděl sloučené pole na dvě části: prvních 5 dní a druhých 5 dní.
daysN = 5
teploty_fix = np.concatenate( [teploty, np.full( ( daysN - teploty.size % daysN ) % daysN, np.nan )] )
teploty_po_N_dnech = np.reshape( teploty_fix, ( -1, daysN ) )

In [ ]:
# vypočítej průměrnou teplotu pro každou část
prumerne_teploty = teploty_po_N_dnech.mean( axis=1 ).round( 3 )
prumerne_teploty_s_popiskem = np.array( list( zip( [
    'Prvních 5 dní - první stanice',
    'Druhých 5 dní - první stanice',
    'Prvních 5 dní - druhá stanice',
    'Druhých 5 dní - druhá stanice',
], prumerne_teploty ) ) )
display( prumerne_teploty_s_popiskem )

<details>
    <summary>▶️ Řešení</summary>
    
    ```python
    stanice_c1_teploty = [21.5, 22.3, 20.7, 19.8, 23.1, 22.6, 20.4, 21.8, 22.9, 21.2]
    stanice_c2_teploty = [18.5, 19.1, 18.7, 17.8, 21.3, 20.6, 18.5, 19.7, 20.5, 19.2]
    
    stanice_c1_teploty_pole = np.array(stanice_c1_teploty)
    stanice_c2_teploty_pole = np.array(stanice_c2_teploty)
    
    spojene_teploty = np.concatenate((stanice_c1_teploty_pole, stanice_c2_teploty_pole))
    
    upraveny_tvar = spojene_teploty.reshape(2, 10)
    prvnich_pet_dni, dalsich_pet_dni = np.hsplit(upraveny_tvar, 5)
    
    prumer_prvnich_deset_dni = np.mean(prvnich_deset_dni)
    prumer_druhych_deset_dni = np.mean(dalsich_deset_dni)
    ```
</details>

<br>

## Univerzální funkce, UFUNCS

---

Výpočty na polích a maticích `numpy` mohou být **velmi rychlé** nebo **velmi pomalé**.

Klíčem k rychlé práci, je použití vektorizovaných operací, které jsou obvykle implementovány prostřednictvím *univerzálními funkcemi*.

Jde tedy o funkce, které pracují na objektech polí a matic, prvek po prvku.
Umožňují efektivní operace na polích, což vede k výrazně rychlejším výsledkům než pomocí běžných **Pythonových funkcí a cyklů**.

Ukázkou může být sčítání hodnot pro dvě dlouhé matice:

In [1]:
import numpy as np

In [2]:
pole_1 = np.random.randint(1, 100, size=10_000_000)

In [3]:
pole_2 = np.random.randint(100, 255, size=10_000_000)

In [4]:
pole_a = np.array([1, 2 ,3])
pole_b = np.array([4, 4, 4])

In [5]:
pole_a + pole_b

array([5, 6, 7])

<br>

Pro sečtení hodnot z obou polí můžeš pracovat s funkce `add`:

In [6]:
%timeit result_loop = [x + y for x, y in zip(pole_1, pole_2)]

1.68 s ± 53.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [7]:
%timeit secteno_ufuncs = np.add(pole_1, pole_2)

31.1 ms ± 440 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


<br>

Můžeš si všimnout, že řešení s výstupem v `secteno_ufuncs` je skoro 5~10x rychlejší.

<br>

Z důvodů použití dynamického, interpretovaného jazyka v rámci CPythonu ti jeho flexibilita neumožní kompilovat jednotlivé operace až na efektivní strojový kód (`01101101110101`).

Určitě existují derivace projektů jako *PyPy*, *Cython*, *Numba*.

### Úvod do UFUNCS

---

Pro mnoho typů operací poskytuje `numpy` praktické rozhraní právě pro tento typ operací,
staticky typované, zkompilované rutiny.

Jedná se o tzv. **vektorizované operace**.

Pro aplikace takových funkcí můžeš jednoduše vybrat konkrétní funkci a aplikovat ji na pole.

In [8]:
pole_3 = np.arange(10)

In [9]:
pole_4 = np.arange(11, 21)

In [10]:
pole_3, pole_4

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]))

In [11]:
pole_3 / pole_4

array([0.        , 0.08333333, 0.15384615, 0.21428571, 0.26666667,
       0.3125    , 0.35294118, 0.38888889, 0.42105263, 0.45      ])

<br>

Počítání přes **ufuncs** je téměř pokaždé efektivnější než aplikace např. obyčejných smyček v Pythonu.

Kromě klasických operátorů, můžeš aplikovat samotné funkce:

In [12]:
np.divide(pole_3, pole_4)

array([0.        , 0.08333333, 0.15384615, 0.21428571, 0.26666667,
       0.3125    , 0.35294118, 0.38888889, 0.42105263, 0.45      ])

<br>

Výpis některých UFUNCS:

| Operátor | Jméno funkce | Popis |
| :- | :- | :- |
| `+` |  `np.add` |  Sčítání (př., `1 + 1 = 2` ) |
| `-` |  `np.subtract` | odčítání (př., `3 - 2 = 1` ) | 
| `-` | `np.negative` |  unární negace (př., `-2` ) | 
| `*` | `np.multiply` |  násobení (př., `2 * 3 = 6` ) |
| `/` | `np.divide` |  dělení (př., `3 / 2 = 1.5` ) |
| `//` |  `np.floor_divide` | celočíselné dělení (př., `3 // 2 = 1` ) |
| `**` | `np.power` | umocňování (př., `2 ** 3 = 8` ) | 
| `%` | `np.mod` | modulo (př., `9 % 4 = 1` ) |

<br>

Další kombinací můžeš pracovat třeba **s absolutními hodnotami**:

In [13]:
negativni_cisla = np.array((-5, -4, -3, -2, -1))

In [14]:
abs(negativni_cisla)

array([5, 4, 3, 2, 1])

In [15]:
type(abs)

builtin_function_or_method

<br>

Pomocí ufuncs použiješ funkci `absolute`, která je ekvivalentem v rámci `numpy`:

In [16]:
np.absolute(negativni_cisla)

array([5, 4, 3, 2, 1])

<br>

Práce s **exponenty** a **umocňování**:

In [ ]:
ciselne_hodnoty = np.arange(6)

In [ ]:
ciselne_hodnoty

In [ ]:
np.exp2(ciselne_hodnoty)      # 2^0, 2^1, 2^2, 2^3, ...

In [ ]:
np.power(3, ciselne_hodnoty)  # 3^0, 3^1, ...

<br>

Knihovna `numpy` potom nabízí další specializované funkce (logaritmické, trigonometrické, aj.)

<br>

##### **🧠 CVIČENÍ 🧠, procvič si základy UFUNCS v NUMPY**

Máte prodejní data dvou obchodů za poslední 3 měsíce. Každý obchod poskytuje seznam svých prodejů za každý měsíc. Vaším úkolem je:

In [ ]:
obchod_1_prodej = [1000, 1200, 1300]
obchod_2_prodej = [900, 1100, 1500]

In [ ]:
# Převést seznamy prodejů na NumPy pole.
import numpy as np

In [ ]:
# 1. Sloučit prodejní data obou obchodů do jednoho pole pomocí funkce concatenate

In [ ]:
# 2. Rozdělit sloučené pole na dvě části, které odpovídají měsícům ..
# .. pod sebou u obou obchodů

In [ ]:
# 3. Vypočítat celkový prodej pro každý měsíc

In [ ]:
# 4. Vypočítat procentuální změnu mezi prvním a druhým měsícem ..
# .. a mezi druhým a třetím měsícem mezi celkovými měs. součty

In [ ]:
#Importy
import numpy as np

#Vstupní data
obchod_1_prodej = [1000, 1200, 1300]
obchod_2_prodej = [900, 1100, 1500]

# Převést seznamy prodejů na NumPy pole.
obchod_1_prodej_np = np.array( obchod_1_prodej )
obchod_2_prodej_np = np.array( obchod_2_prodej )


# Sloučit prodejní data obou obchodů do jednoho pole pomocí funkce concatenate
obchody_prodej = np.concatenate( [ obchod_1_prodej_np, obchod_2_prodej_np ] )
display( obchody_prodej )

# Rozdělit sloučené pole na dvě části, které odpovídají měsícům pod sebou u obou obchodů
rozdeleni_mesice = np.reshape( obchody_prodej, (-1, 3) ).T
display( rozdeleni_mesice )

# Vypočítat celkový prodej pro každý měsíc
celkove_prodeje = rozdeleni_mesice.sum( axis = 1 )
display( celkove_prodeje )

# Vypočítat procentuální změnu mezi prvním a druhým měsícem a mezi druhým a třetím měsícem
procentualni_zmena = ( np.diff( celkove_prodeje ) / celkove_prodeje[:2] * 100 ).round( 3 )
display( procentualni_zmena )

<details>
    <summary>▶️ Řešení</summary>
    
    ```python
    obchod_1_prodej = [1000, 1200, 1300]
    obchod_2_prodej = [900, 1100, 1500]
    
    import numpy as np

    # 1. Sloučit prodejní data obou obchodů do jednoho pole pomocí funkce concatenate
    sloucene_prodeje = np.concatenate((obchod_1_prodej_pole, obchod_2_prodej_pole))
    
    # 2. Rozdělit sloučené pole na dvě části, které odpovídají měsícům ..
    # .. pod sebou u obou obchodů
    rozdelene_po_mesicich = sloucene_prodeje.reshape(2, -1)
    
    # 3. Vypočítat celkový prodej pro každý měsíc
    mesic_1, mesic_2, mesic_3 = np.hsplit(rozdelene_po_mesicich, 3)
    celkem_mesice = np.array((mesic_1.sum(), mesic_2.sum(), mesic_3.sum()))
    
    # 4. Vypočítat procentuální změnu mezi prvním a druhým měsícem ..
    # .. a mezi druhým a třetím měsícem mezi celkovými měs. součty
    rozdily = np.diff(celkem_mesice)
    np.divide(rozdily, celkem_mesice[:2]) * 100
    ```
</details>

---